FROM golang:1.23 AS build

WORKDIR /app
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o tic_tac_toe_app ./cmd

FROM alpine
WORKDIR /
COPY --from=build /app/tic_tac_toe_app tic_tac_toe_app
EXPOSE 8080
ENTRYPOINT ["./tic_tac_toe_app","--port=8080"]

