###
# @name games
POST http://localhost:8080/new_game
Content-Type: application/json

{}

###
# @name move
POST http://localhost:8080/move
Content-Type: application/json

{
  "id": "590a09aa-979d-44ff-a931-f81fc1badd40",
  "row": 1,
  "col": 1,
  "player": "X"
}
