###
# @name games
POST http://localhost:8080/new_game
Content-Type: application/json

{}


###
# @name status
POST http://localhost:8080/status
Content-Type: application/json

{
  "id": "d4384b19-5d9a-41e4-87cf-a94925f687c9"
}

###
# @name move
POST http://localhost:8080/move
Content-Type: application/json

{
  "id": "590a09aa-979d-44ff-a931-f81fc1badd40",
  "row": 1,
  "col": 1,
  "player": "X"
}
